services:
  dns:
    image: coredns/coredns:1.11.3
    container_name: dotoblo_dns
    restart: unless-stopped
    command: ["-conf", "/etc/coredns/Corefile"]
    volumes:
      - ./dns/coredns/Corefile:/etc/coredns/Corefile:ro
    ports:
      - "53:53/udp"
      - "53:53/tcp"

